baseurl = "https://www.hasor.net/web/"
title = "Hasor - 小而美大而全"
theme = "themes"
themesDir = "."
languageCode = "en-us"

defaultContentLanguage = "en"
disqusShortname = "say somthing?"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/index.html"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/index.html"
    weight = 2

[[menu.main]]
    name = "Documentation"
    url  = "https://www.hasor.net/guide/index.html"
    weight = 3

[[menu.main]]
    name = "API"
    url  = "https://www.hasor.net/apis/hasor/3.1.x/3.1.3/index.html"
    weight = 4

#[[menu.main]]
#    name = "Blog"
#    url  = "/blog/"
#    weight = 5

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/index.html"
    weight = 6

[params]
    viewMorePostLink = ["/blog/","/project/"]
    email = "your@email.com"
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[Permalinks]
    blog    = "/blog/:year/:month/:day/:filename/"
    project = "/project/:filename/"

[params.topbar]
    enable = false
    text = """ """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.see_more]
    enable = true
    title = "Hasor"
    subtitle = "一款强大的 Java 应用开发框架，它的目标是提供一个简单、且必要的全栈环境。开发者可以在此基础上快速开发软件。"

[params.features]
    enable = true

[params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
